# Generated by Django 4.0.1 on 2022-03-29 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stateloan',
            fields=[
                ('state_id', models.AutoField(primary_key=True, serialize=False)),
                ('state_name', models.CharField(max_length=100)),
                ('amount_lended', models.IntegerField()),
                ('amount_recovered', models.IntegerField()),
            ],
        ),
    ]
